// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Quotation.Data.Contexts;

#nullable disable

namespace Quotation.Data.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20260505120000_AddVehicleDetailsToSpacer")]
    partial class AddVehicleDetailsToSpacer
    {
    }
}
